core/templates/dashboard.html
core/views.py

fix of hiding offline and brokeroff queues ,  tables "Job attribute summary" and "Overall error summary" accessible via JSON

two changes

---

core/views.py

recovery statenotupdated request in tasks

---

core/buildmonitor/templates/globalviewDemo.html

added comment to buildmonitor/templates/globalviewDemo.html

Buildmonitor

---

core/libs/DataProgressPlot.py
core/settings/base.py
core/templates/userProfile.html
core/urls.py
core/views.py

1) userProfile function
2) userProfileData

Version 1 which contained:

---

core/harvester/utils.py
core/libs/TasksErrorCodesAnalyser.py
core/libs/task.py
core/pandajob/SQLLookups.py
core/schedresource/utils.py
core/views.py

Details in https://its.cern.ch/jira/browse/ATLASPANDA-613

to fix pandamon@postgres

---

core/templates/taskList.html
core/templates/userDash.html
core/templates/userInfoHelp.html

Minor syntax corrections

---

core/common/models.py
core/views.py

Add check if nfilesmissing exists for a dataset & update model

ATLASPANDA-799

---

core/iDDS/DAGvisualization.py
core/iDDS/rawsqlquery.py
core/iDDS/templates/workflows.html
core/iDDS/tests.py
core/iDDS/useconstants.py
core/iDDS/utils.py
core/templates/taskList.html
core/views.py

plus some clean up and styling improvement of taskList

idds | add support of selection tasks by idds request id and transform status

---

core/art/templates/artJobs.html
core/art/templates/artTasks.html
core/art/templates/artTest.html
core/art/templates/artTestSearchHelp.html
core/art/urls.py
core/art/utils.py
core/art/views.py

Added package as expected parameter for ART test page as it is not forbidden to use the same test name across packages
Show error message on page instead of JSON response

ART improvements

---

core/art/views.py

art | fix reports

---

core/buildmonitor/templates/civiewDemo.html

The CI view template is updated with the color palette optimized for colorblind users, particularly for those with reduced sensitivity to green color. The colors of this palette is used to highlight results for different MR. Details are in https://its.cern.ch/jira/browse/ATLINFR-5064

new colorlind-friendly palette is implemented for CI view

---

core/views.py

core | add check of POST request as an attempt to catch UnreadablePostError

---

core/art/templates/artTest.html
core/art/views.py
core/dashboards/jobsummarynucleus.py
core/libs/job.py
core/servicemonitoring/utils.py
core/views.py

servicemonitoring | increase ttr threshold to report degraded state
art | add job error message to test page
core | fix dash world view

various fixes & updates

---

core/static/css/page-sections.css
core/static/js/app.js
core/static/js/datatables/renderEllipsisCustom.js
core/templates/jobList.html
core/templates/userDash.html
core/views.py

+ user dash | add word breaks to long strings in tooltips

jobList | add button to check logs availability

---

core/libs/job.py
core/templates/fileList.html
core/views.py

1. Fixing N events column on the jobs page
2. Adding a new "N events allocated column" (endevent + 1 - startevent) to the files table on the files list page

Fixing an existing view and adding a new feature

---

core/buildmonitor/templates/compview_eosDemo.html
core/buildmonitor/templates/testview_eosDemo.html
core/buildmonitor/urls.py
core/buildmonitor/viewscomps_eos.py
core/buildmonitor/viewstests_eos.py

Added two views of compilation, test results linked to new webEOS based log storage

new views of compilation, test results linked to new webEOS storage

---

core/buildmonitor/templates/testviewDemo.html
core/buildmonitor/templates/testview_eosDemo.html
core/buildmonitor/viewscomps.py
core/buildmonitor/viewscomps_eos.py
core/buildmonitor/viewstests.py
core/buildmonitor/viewstests_eos.py

updates: forcing AFS or EOS storage usage (according to DB specification), improve style of timeout icon

Update: choice of AFS or EOS storage (based on DB info); style of timeout icon

---

core/common/models.py
core/dashboards/eventservice.py
core/dashboards/jobsummaryregion.py
core/libs/exlib.py
core/pandajob/utils.py
core/static/css/page-sections.css
core/templates/jobInfo.html
core/templates/jobInfoES.html
core/templates/jobList.html
core/templates/resourceTypeList.html
core/urls.py
core/views.py

+ add resource types page
+ small clean up

core | ATLASPANDA-898 add calculation of allocated maxram from resourcetype

---

Dockerfile

Attempt to install python3.11 and django 5.0.8 to be able to support oracledb

Attempt to install python3.11 and django 5.0.8 to be able to support oracledb

---

core/settings/config.py

Add support for the ATLAS testbed running on Oracle

Add support for the ATLAS testbed running on Oracle

---

core/buildmonitor/templates/civiewDemo.html
core/buildmonitor/templates/globalviewDemo.html
core/buildmonitor/templates/nviewDemo.html

Lists of informational links have been updated for the three CI and Nightly Systems views. Explanations of the table headers have also been added to facilitate a clearer understanding of the table contents.

added links to new documents, added explanations of table headers

---

Dockerfile
docker/yum.repos.d/almalinux-appstream_1.repo
docker/yum.repos.d/almalinux-baseos_1.repo

I tested this one. It works
https://github.com/wguanicedew/panda-bigmon-core/actions/runs/11968699140

add almalinux 9 yum repo

---

core/buildmonitor/templates/civiewDemo.html
core/buildmonitor/templates/globalviewDemo.html
core/buildmonitor/templates/nviewDemo.html
core/buildmonitor/viewsci.py
core/buildmonitor/viewsglobal.py
core/buildmonitor/viewsn.py

As requested in https://its.cern.ch/jira/browse/ATLINFR-5097, the number of timed-out tests is added to the column showing the CI or CTest results in three views.

added the number of timed-out tests to the CTest column

---

core/buildmonitor/templates/nviewDemo.html
core/buildmonitor/viewsci.py

replacement of ">=" to ">" in one line of nviewDemo.html and correction of few list indices in viewsci.py

fixing misprints in changes for pull request #423 

---

core/datacarousel/templates/dataCarouselDash.html
core/datacarousel/utils.py

1. Fixed URL parameters that were not passed to the python code.
2. Added "cancelled" status for analysistask.

ATLASPANDA-1285 Improved DC dashboard

---

core/panda_client/utils.py

Code cleanup for the debug set mode button

ATLASPANDA-1470: Code cleanup

---

core/panda_client/http_client.py
core/panda_client/net_utils.py
core/panda_client/thread_utils.py
core/panda_client/utils.py
core/panda_client/utils_old.py
core/panda_client/views.py
core/templates/jobInfo.html
core/templates/jobList.html
core/templates/taskInfo.html

- Adding missing files
- Removed unused code related to the debug mode button
- Simplified logic to avoid redundancy

ATLASPANDA-1470: Cleanup debug mode button code

---

core/templates/taskInfo.html

- Removed trailing slash from Rucio container links (Rucio UI does not accept it).
- Dropped redundant scope from the "name=" query parameter to match the expected format.

ATLASPANDA-1513: Fix Rucio links for input containers
